[package]
name = "gas-service"
version = "0.1.0"
edition = "2021"

[package.metadata.clippy]
allow = ["too_many_arguments"]

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
base64.workspace = true
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
thiserror.workspace = true
gateway = { workspace = true, features = ["no-entrypoint"] }
auth-weighted = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test.workspace = true
anyhow.workspace = true
hex.workspace = true
solana-sdk.workspace = true
