[package]
name = "gas-service"
version = "0.1.0"
edition = "2021"

[package.metadata.clippy]
allow = ["too_many_arguments"]

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
axelar-message-primitives.workspace = true
base64.workspace = true
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
