[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
base64.workspace = true
hex = "0.4.3"
num-derive = "0.4.1"
num-traits = "0.2.17"
slice-iterator = { path = "../../helpers/slice-iterator" }
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
arrayref = "0.3.7"
random-array = { path = "../../helpers/random-array" }
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
