[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
auth-weighted = { workspace = true, features = ["no-entrypoint"] }
base64.workspace = true
bcs.workspace = true
borsh.workspace = true
connection-router.workspace = true
cosmwasm-std.workspace = true
itertools.workspace = true
multisig-prover.workspace = true
multisig.workspace = true
num-derive = "0.4.1"
num-traits = "0.2.17"
serde.workspace = true
sha3.workspace = true
slice-iterator.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
random-array.workspace = true
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
test-fixtures.workspace = true
