[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
auth-weighted = { workspace = true, features = ["no-entrypoint"] }
base64.workspace = true
borsh.workspace = true
bcs = "0.1.6"
num-derive = "0.4.1"
num-traits = "0.2.17"
slice-iterator.workspace = true
solana-program.workspace = true
thiserror.workspace = true
multisig-prover.workspace = true
connection-router.workspace = true
multisig.workspace = true
cosmwasm-std.workspace = true
serde.workspace = true
itertools = "0.12.0"

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
random-array.workspace = true
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
fastrand = "2"
rand_core = { version = "0.6.4", features = ["getrandom"] }
axelar-wasm-std.workspace = true
k256 = { version = "0.13.3", features = ["ecdsa"] }
