[package]
name = "gmp-gateway"
version = "0.1.0"
edition = "2021"

[lints.rust]
missing_docs = "warn"
rust_2018_idioms = "deny"
unreachable_pub = "warn"
unused_imports = "warn"
unused_must_use = "deny"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
axelar-message-primitives.workspace = true
axelar-rkyv-encoding.workspace = true
base64.workspace = true
bincode.workspace = true
bitflags.workspace = true
borsh.workspace = true
hex.workspace = true
itertools.workspace = true
libsecp256k1.workspace = true
num-derive.workspace = true
num-traits.workspace = true
program-utils.workspace = true
rkyv.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
sha3.workspace = true
solana-client.workspace = true
solana-logger.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-fixtures.workspace = true
typed-builder.workspace = true
