[package]
name = "auth-weighted"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
base64.workspace = true
bnum.workspace = true
borsh.workspace = true
hex.workspace = true
k256.workspace = true
libsecp256k1.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-fixtures.workspace = true
