[workspace]
members = ["components/*", "xtask-relayer", "xtask-solana-client"]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = true
panic = 'abort'

[workspace.dependencies]
anchor-client = "0.28.0"
anyhow = "1.0"
clap = { version = "4.4.8", features = ["derive"] }
gateway = { path = "../solana/programs/gateway", features = ["no-entrypoint"] }
serde = "1.0"
serde_json = "1.0"
solana-client = "1.16.18"
solana-program = "1.16.18"
solana-sdk = "1.16.18"
shellexpand = "3.1.0"
log = "0.4.20"
env_logger = "0.10.0"
