# https://github.com/crate-ci/typos/blob/master/docs/reference.md
[default.extend-identifiers]
itswMJtRUe2vd46rb5kDmYzfBHHej4PyX4twgnbT1TG = "itswMJtRUe2vd46rb5kDmYzfBHHej4PyX4twgnbT1TG"

[files]
extend-exclude = [
  "axelar-amplifier",
  "evm-contracts/lib/*",
  "solana/xtask/solana-devnet.json",
  "solana/xtask/devnet-amplifier.json",
]

[default]
extend-ignore-identifiers-re = [
  "gtwgM94UYHwBh3g7rWi1tcpkgELxHQRLPpPHsaECW57",
]
