[package]
name = "test-fixtures"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
borsh.workspace = true
itertools.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
typed-builder.workspace = true

axelar-executable-old.workspace = true
axelar-message-primitives.workspace = true
axelar-rkyv-encoding = { workspace = true, features = ["test-fixtures"] }
interchain-token-transfer-gmp = { workspace = true }
solana-program-test = { workspace = true }

gas-service = { workspace = true, features = ["no-entrypoint"] }
gateway = { workspace = true, features = ["no-entrypoint"] }

spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
bincode.workspace = true
