[package]
name = "test-fixtures"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axelar-wasm-std.workspace = true
bcs.workspace = true
connection-router.workspace = true
cosmwasm-std.workspace = true
fastrand = "2"
hex.workspace = true
itertools.workspace = true
libsecp256k1.workspace = true
multisig-prover.workspace = true
multisig.workspace = true
rand_core = { version = "0.6.4", features = ["getrandom"] }
signature.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
borsh.workspace = true
tokio.workspace = true

axelar-executable.workspace = true
axelar-message-primitives.workspace = true
solana-program-test = { workspace = true }
interchain-token-transfer-gmp = { workspace = true }

token-manager = { workspace = true, features = ["no-entrypoint"] }
spl-token = { workspace = true, features = ["no-entrypoint"] }
interchain-token-service = { workspace = true, features = ["no-entrypoint"] }
gas-service = { workspace = true, features = ["no-entrypoint"] }
gateway = { workspace = true, features = ["no-entrypoint"] }
account-group = { workspace = true, features = ["no-entrypoint"] }
interchain-address-tracker = { workspace = true, features = ["no-entrypoint"] }
