[package]
name = "test-fixtures"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axelar-wasm-std.workspace = true
bcs.workspace = true
connection-router.workspace = true
cosmwasm-std.workspace = true
hex.workspace = true
itertools.workspace = true
libsecp256k1.workspace = true
rand.workspace = true
signature.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
borsh.workspace = true
tokio.workspace = true

axelar-executable.workspace = true
axelar-message-primitives.workspace = true
axelar-rkyv-encoding = {workspace = true, features = ["test-fixtures"]}
solana-program-test = { workspace = true }
interchain-token-transfer-gmp = { workspace = true }

spl-token = { workspace = true, features = ["no-entrypoint"] }
gas-service = { workspace = true, features = ["no-entrypoint"] }
gateway = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
bincode.workspace = true
