name: 'Setup Repo Action'
description: 'A reusable composite action that setups rust and other common tasks'
inputs:
  toolchain:
    description: 'Override the default (nightly) toolchain to install'
    required: false
    default: 'nightly-2024-01-30'

runs:
  using: 'composite'
  steps:
    - name: Install nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}

    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        cache-on-failure: true
        workspaces: |
          solana


    - name: Install cargo-make
      shell: bash
      run: cargo install --debug cargo-make
