[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
anyhow.workspace = true
axum.workspace = true
bcs.workspace = true
borsh.workspace = true
clap = { workspace = true, features = ["derive"] }
dashmap.workspace = true
futures-concurrency.workspace = true
futures-util.workspace = true
futures.workspace = true
hex.workspace = true
prost.workspace = true
serde.workspace = true
solana-client.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
solana-transaction-status.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
trait-variant.workspace = true
url.workspace = true
tower = "0.4.13"

[dependencies.gmp-gateway]
path = "../../../solana/programs/gateway"
features = ["no-entrypoint"]

[dependencies.axelar-executable]
path = "../../../solana/helpers/axelar-executable"

[dev-dependencies]
reqwest = "0.12"
temp-env = "0.3.6"

[build-dependencies]
tonic-build.workspace = true

[package.metadata.cargo-machete]
ignored = ["prost"]
