[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
amplifier-api = { path = "../amplifier-api" }
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
env_logger.workspace = true
futures-util.workspace = true
futures.workspace = true
hex.workspace = true
log.workspace = true
multisig-prover.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
solana-client.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
solana-transaction-status.workspace = true
sqlx.workspace = true
tendermint-rpc.workspace = true
thiserror.workspace = true
tiny-keccak.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tonic.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
figment.workspace = true


[dev-dependencies]
reqwest = "0.12"

[dependencies.gmp-gateway]
path = "../../../solana/programs/gateway"
features = ["no-entrypoint"]

[dependencies.axelar-executable]
path = "../../../solana/helpers/axelar-executable"
