[workspace]
members = ["programs/*", "helpers/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
base64 = "0.21"
bcs = "0.1.6"
bnum = { version = "0.10", features = ["serde"] }
borsh = { version = "1", features = ["derive"] }
bytemuck = "1"
cosmwasm-std = "1.5"
hex = "0.4"
itertools = "0.12.0"
k256 = { version = "0.13.3", features = ["ecdsa"] }
libsecp256k1 = "0.7.0"
num-derive = "0.4"
num-traits = "0.2"
serde = "1"
sha3 = "0.10.8"
signature = "2"
solana-program = "1.18.0"
solana-program-test = "1.18.0"
solana-sdk = "1.18.0"
thiserror = "1"
ethers-core = "2"
spl-token = "4.0.0"
spl-associated-token-account = "2.3.0"

# solana programs
auth-weighted = { path = "programs/auth-weighted" }
account-group = { path = "programs/account-group" }
gateway = { path = "programs/gateway", package = "gmp-gateway" }
gas-service = { path = "programs/gas-service" }
token-manager = { path = "programs/token-manager" }
interchain-token-service = { path = "programs/interchain-token-service" }
interchain-address-tracker = { path = "programs/interchain-address-tracker" }
axelar-solana-memo-program = { path = "programs/axelar-solana-memo-program" }

# helper crates
program-utils = { path = "helpers/program-utils" }
interchain-token-transfer-gmp = { path = "helpers/interchain-token-transfer-gmp" }
test-fixtures = { path = "helpers/test-fixtures" }
axelar-executable = { path = "helpers/axelar-executable" }
axelar-message-primitives = { path = "helpers/axelar-message-primitives" }


[workspace.dependencies.multisig]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.multisig-prover]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.connection-router]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.axelar-wasm-std]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1


[patch.crates-io]
# aes-gcm-siv 0.10.3 and curve25519-dalek 3.x pin zeroize to <1.4
# which conflicts with other dependencies requiring zeroize ^1.5.
# We’re patching both crates to unpin zeroize.
#
# For aes-gcm-siv we’re using the same revision Solana uses in
# an (as of now) unreleased commit, see
# https://github.com/solana-labs/solana/commit/01f1bf27994d9813fadfcd134befd3a449aaa0bd
#
# For curve25519-dalek we’re using commit from a PR, see
# https://github.com/dalek-cryptography/curve25519-dalek/pull/606
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef" }
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", rev = "8274d5cbb6fc3f38cdc742b4798173895cd2a290" }
