[workspace]
members = ["programs/*", "helpers/*", "common", "xtask-relayer", "xtask-solana-client"]
resolver = "2"

[workspace.dependencies]
program-utils = { path = "programs/program-utils" }
anchor-client = "0.29.0"
anchor-lang = { version = "0.29.0" }
anyhow = "1"
base64 = "0.21"
borsh = "0.10"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
num-derive = "0.4"
num-traits = "0.2"
regex = "1"
serde = "1"
serde_json = "1"
shellexpand = "3.1.0"
solana-client = "1.17.9"
solana-program = "1.17.9"
solana-sdk = "1.17.9"
solana-transaction-status = "1.17.9"
tokio = { version = "1", features = ["full"] }
solana-program-test = "1.17.9"
ethnum = { version = "1.5.0", features = ["serde"]}
thiserror = "1"
hex = "0.4.3"
secp256k1 ="0.28.0"
rand = "0.8.5"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
