[workspace]
members = ["programs/*", "common", "xtask-relayer", "xtask-solana-client"]
resolver = "2"

[workspace.dependencies]
anchor-client = "0.29.0"
anchor-lang = { version = "0.29.0" }
anyhow = "1"
base64 = "0.21"
borsh = "0.10"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
regex = "1"
serde = "1"
serde_json = "1"
shellexpand = "3.1.0"
solana-client = "1.17.6"
solana-program = "1.17.6"
solana-sdk = "1.17.6"
solana-transaction-status = "1.17.6"
tokio = { version = "1", features = ["full"] }


[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
