[workspace]
members = ["programs/*", "helpers/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.29.0"
anyhow = "1"
base64 = "0.21"
borsh = { version = "1", features = ["derive"] }
bnum = { version = "0.10", features = ["serde", "nightly"] }
hex = "0.4.3"
num-derive = "0.4"
num-traits = "0.2"
solana-program = "1.17.12"
solana-program-test = "1.17.12"
solana-sdk = "1.17.12"
thiserror = "1"
cosmwasm-std = "1.5"
serde = "1"
auth-weighted = { path = "programs/auth-weighted" }

# helper crates
program-utils = { path = "helpers/program-utils" }
random-array = { path = "helpers/random-array" }
slice-iterator = { path = "helpers/slice-iterator" }
operator = { path = "programs/operator" }


[workspace.dependencies.multisig]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.multisig-prover]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.connection-router]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1


[patch.crates-io]
# aes-gcm-siv 0.10.3 and curve25519-dalek 3.x pin zeroize to <1.4
# which conflicts with other dependencies requiring zeroize ^1.5.
# We’re patching both crates to unpin zeroize.
#
# For aes-gcm-siv we’re using the same revision Solana uses in
# an (as of now) unreleased commit, see
# https://github.com/solana-labs/solana/commit/01f1bf27994d9813fadfcd134befd3a449aaa0bd
#
# For curve25519-dalek we’re using commit from a PR, see
# https://github.com/dalek-cryptography/curve25519-dalek/pull/606
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef" }
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", rev = "8274d5cbb6fc3f38cdc742b4798173895cd2a290" }
