[workspace]
members = ["programs/*", "helpers/*", "xtask", "crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
base64 = "0.21"
bcs = "0.1.6"
bnum = { version = "0.10", features = ["serde"] }
borsh = { version = "1", features = ["derive"] }
bs58 = "0.5.1"
bytemuck = "1"
cosmwasm-schema = "2"
cosmwasm-std = "1.5"
ethers = "2"
ethers-core = "2"
hex = "0.4"
itertools = "0.12"
ed25519-dalek = "2"
k256 = { version = "0.13", features = ["ecdsa"] }
libsecp256k1 = { version = "0.6", default-features = false }
num-derive = "0.4"
xshell = "0.2"
num-traits = "0.2"
rkyv = "0.7"
rstest = "0.19"
serde = "1"
sha3 = "0.10"
signature = "2"
solana-program = "2.0.1"
solana-program-test = "2.0.1"
solana-sdk = "2.0.1"
serde_json = "1"
spl-associated-token-account = "2.3"
spl-token = "4.0.0"
test-log = { version = "0.2", features = ["trace"], default-features = false }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
bincode = "1"
reqwest = { version = "0.12", features = ["json", "stream"] }
futures = "0.3"
rand = "0.8"

# solana programs
gateway = { path = "programs/gateway", package = "gmp-gateway" }
gas-service = { path = "programs/gas-service" }
axelar-solana-memo-program = { path = "programs/axelar-solana-memo-program" }

# helper crates
program-utils = { path = "helpers/program-utils" }
interchain-token-transfer-gmp = { path = "helpers/interchain-token-transfer-gmp" }
test-fixtures = { path = "helpers/test-fixtures" }
axelar-executable = { path = "helpers/axelar-executable" }
axelar-message-primitives = { path = "helpers/axelar-message-primitives" }
evm-contracts-rs = { path = "helpers/evm-contracts-rs" }
evm-contracts-test-suite = { path = "helpers/evm-contracts-test-suite" }
axelar-rkyv-encoding = { path = "crates/axelar-rkyv-encoding" }

[workspace.dependencies.multisig]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.multisig-prover]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.connection-router]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[workspace.dependencies.axelar-wasm-std]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[patch.crates-io]
# curve25519-dalek 3.x pin zeroize to <1.4
# which conflicts with other dependencies requiring zeroize ^1.5.
# We’re patching it here to unpin zeroize, using commit from a PR, see
# https://github.com/dalek-cryptography/curve25519-dalek/pull/606
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", rev = "8274d5cbb6fc3f38cdc742b4798173895cd2a290" }
