[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true

[tasks.local-ci]
workspace = false
dependencies = ["check", "test", "unused-deps"]

[tasks.typos]
workspace = false
install_crate = "typos-cli"
command = "typos"

[tasks.fmt]
workspace = false
command = "cargo"
args = [
  "fmt",
  "--package",
  "axelar-executable",
  "--package",
  "axelar-message-primitives",
  "--package",
  "evm-contracts-rs",
  "--package",
  "evm-contracts-test-suite",
  "--package",
  "interchain-token-transfer-gmp",
  "--package",
  "governance-gmp",
  "--package",
  "program-utils",
  "--package",
  "test-fixtures",
  "--package",
  "xtask",
  "--package",
  "its-instruction-builder",
  "--",
  "--emit=files",
]
dependencies = ["fmt-clippy"]

[tasks.fmt-clippy]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty", "--allow-staged", "--workspace"]

[tasks.unused-deps]
workspace = false
install_crate = "cargo-machete"
install_crate_args = ["--locked"]
command = "cargo"
args = ["machete"]

[tasks.check]
dependencies = ["fmt-check", "clippy-check"]

[tasks.fmt-check]
workspace = false
command = "cargo"
args = [
  "fmt",
  "--package",
  "axelar-executable",
  "--package",
  "axelar-message-primitives",
  "--package",
  "evm-contracts-rs",
  "--package",
  "evm-contracts-test-suite",
  "--package",
  "interchain-token-transfer-gmp",
  "--package",
  "governance-gmp",
  "--package",
  "program-utils",
  "--package",
  "test-fixtures",
  "--package",
  "xtask",
  "--package",
  "its-instruction-builder",
  "--check",
]

[tasks.clippy-check]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--no-deps", "--all-targets", "--workspace", "--locked", "--", "-D", "warnings"]

[tasks.test]
workspace = false
# solana bpf tests. Run them like this because order of how they're run is
# important to generate the appropriate .so artifacts for subsequent tests
script = """
cargo test-sbf --package gas-service
cargo test-sbf --package gmp-gateway
cargo test-sbf --package axelar-solana-gateway
cargo test-sbf --package governance
cargo test-sbf --package axelar-solana-memo-program
cargo test-sbf --package axelar-solana-multicall
cargo test-sbf --package axelar-solana-its
"""
dependencies = [
  # normal tests that don't get picked up by test-sbf
  "test-non-sbf",
]

[tasks.build-sbf]
workspace = false
command = "cargo"
args = ["build-sbf"]

[tasks.test-non-sbf]
workspace = false
command = "cargo"
args = [
  "test",
  "--package",
  "axelar-executable",
  "--package",
  "axelar-message-primitives",
  "--package",
  "evm-contracts-rs",
  "--package",
  "evm-contracts-test-suite",
  "--package",
  "interchain-token-transfer-gmp",
  "--package",
  "governance-gmp",
  "--package",
  "program-utils",
  "--package",
  "test-fixtures",
  "--package",
  "xtask",
  "--package",
  "its-instruction-builder",
]

[tasks.audit]
workspace = false
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]
