[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true

[tasks.local-ci]
workspace = false
dependencies = ["check", "test", "unused-deps"]

[tasks.fmt]
workspace = false
command = "cargo"
args = ["fmt", "--all", "--", "--emit=files"]
dependencies = ["fmt-clippy"]

[tasks.fmt-clippy]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty", "--allow-staged", "--workspace"]

[tasks.unused-deps]
workspace = false
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps", "--all-targets", "--backend=depinfo"]

[tasks.check]
dependencies = ["fmt-check", "clippy-check"]

[tasks.fmt-check]
workspace = false
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy-check]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--workspace", "--locked", "--", "-D", "warnings"]

[tasks.test]
workspace = false
command = "cargo"
# solana bpf tests
args = ["test-sbf", "--workspace"]
dependencies = [
    # normal tests that don't get picked up by test-sbf
    "test-non-sbf",
    # For some reason, the `test-sbf` task doesn't pick up some Solana programs,
    # so we pre-build them beforehand
    "build-sbf"
]

[tasks.build-sbf]
workspace = false
command = "cargo"
args = ["build-sbf"]

[tasks.test-non-sbf]
workspace = false
command = "cargo"
args = [
    "test",
    "--package",
    "test-fixtures",
    "--package",
    "interchain-token-transfer-gmp",
    "--package",
    "program-utils",
]

[tasks.audit]
workspace = false
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]
