[package]
name = "interchain-address-tracker"
version = "0.1.0"
description = "Port of the https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/66325132bde3f61d2c18748cfcd3e181b063ea00/contracts/utils/InterchainAddressTracker.sol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program.workspace = true
thiserror.workspace = true
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
gateway = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
