[package]
name = "program-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh.workspace = true
rkyv.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
