[package]
name = "program-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
solana-program.workspace = true
thiserror.workspace = true
borsh.workspace = true

[dev-dependencies]
