[package]
name = "axelar-rkyv-encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
bnum.workspace = true
rkyv = { workspace = true, features = ["validation"] }
sha3.workspace = true
thiserror.workspace = true
rand = { workspace = true, optional = true }
libsecp-rand = { package = "rand", version = "0.7", optional = true }
ed25519-dalek = { workspace = true }
hex.workspace = true
bs58.workspace = true
libsecp256k1 = { workspace = true, default-features = false, features = ["static-context", "hmac"] }

[dev-dependencies]
ed25519-dalek = { workspace = true, features = ["rand_core", "digest"] }
rand.workspace = true
libsecp-rand = { package = "rand", version = "0.7" }

[features]
default = []
test-fixtures = [
  "dep:rand",
  "dep:libsecp-rand",
  "libsecp-rand/getrandom",
  "rand/getrandom",
  "ed25519-dalek/rand_core",
  "ed25519-dalek/digest",
]
