[package]
name = "axelar-solana-its"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
axelar-executable-old = { workspace = true }
axelar-message-primitives.workspace = true
axelar-rkyv-encoding.workspace = true
borsh.workspace = true
gateway = { workspace = true, features = ["no-entrypoint"] }
interchain-token-transfer-gmp.workspace = true
itertools.workspace = true
program-utils.workspace = true
role-management.workspace = true
rkyv.workspace = true
solana-program.workspace = true
spl-associated-token-account = { workspace = true, features = ["no-entrypoint"] }
spl-pod.workspace = true
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint", "serde-traits"] }
spl-token-metadata-interface = { workspace = true, features = ["serde-traits"] }
typed-builder.workspace = true

[dev-dependencies]
axelar-solana-memo-program = { workspace = true, features = ["no-entrypoint"] }
evm-contracts-test-suite.workspace = true
rstest.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-fixtures.workspace = true
