[package]
name = "solana-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
env_logger.workspace = true
log.workspace = true
solana-client.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
