[package]
name = "eiger-solana-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
solana-client.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
gateway = { path = "../../../solana/programs/gateway", package = "gmp-gateway" }
anyhow.workspace = true
