[package]
name = "axelar-solana-gas-service-events"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
solana-program.workspace = true
thiserror.workspace = true

[lints]
workspace = true
