tm_jsonrpc = "http://devnet-amplifier.axelar.dev:26657"
tm_grpc = "http://devnet-amplifier.axelar.dev:9090"
event_buffer_cap = 1000

[service_registry]
cosmwasm_contract = "axelar1c9fkszt5lq34vvvlat3fxj6yv7ejtqapz04e97vtc9m5z9cwnamq8zjlhz"

[broadcast]
batch_gas_limit = "1000000"
broadcast_interval = "1s"
chain_id = "devnet-amplifier"
gas_adjustment = "2"
gas_price = "0.00005uamplifier"
queue_cap = "1000"
tx_fetch_interval = "600ms"
tx_fetch_max_retries = "10"

[tofnd_config]
batch_gas_limit = "10000000"
key_uid = "axelar"
party_uid = "ampd"
url = "http://127.0.0.1:50051"

[[handlers]]
cosmwasm_contract = "axelar1zwps4z7at8d6kn7jgsafqcp0wws50dv7l93h7pw4pvnrmh90cspsdar9rd"
type = "MultisigSigner"

[[handlers]]
chain_name = "solana"
chain_rpc_url = "https://api.devnet.solana.com"
cosmwasm_contract = "axelar1q7fct2kgpjxyxj7vvt9468aycr30cw7je9ugjgqwskc40pkfu0ns5vfew3"
type = "SolanaMsgVerifier"
max_tx_cache_entries = 6

[[handlers]]
chain_name = "solana"
chain_rpc_url = "https://api.devnet.solana.com"
cosmwasm_contract = "axelar1q7fct2kgpjxyxj7vvt9468aycr30cw7je9ugjgqwskc40pkfu0ns5vfew3"
type = "SolanaVerifierSetVerifier"
