[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[lints.clippy]
complexity = { priority = -1, level = "deny" }
correctness = { priority = -1, level = "deny" }
pedantic = { priority = -1, level = "deny" }

[lints.rust]
unused_imports = "warn"
rust_2018_idioms = "deny"
missing_docs = "warn"
unreachable_pub = "warn"
unused_crate_dependencies = "warn"
unused_must_use = "deny"


[dependencies]
anyhow.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
tokio.workspace = true
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
xshell = "0.2.6"
solana-program.workspace = true
solana-sdk.workspace = true
gmp-gateway = { path = "./../programs/gateway" }
axelar-message-primitives = { path = "./../helpers/axelar-message-primitives" }
solana-client = "1.18.13"
url = "2.5.0"
toml = "0.8.13"
serde.workspace = true
solana-cli-config = "1.18.14"

[dev-dependencies]
indoc = "2.0.5"
solana-sdk.workspace = true
hex.workspace = true
solana-streamer = "1.18.12"
solana-test-validator = "1.18.12"
tempfile = "3.10.1"
serial_test = "3.1.1"
solana-logger = "1.18.12"
borsh.workspace = true
