operator = "5Jja5kAvCFkixQSQhKpKWgWRx8FX6eh3FXH7oqJ98x7"

[[signers]]
# cat ~/.ampd/state.json
# {"handlers":{"multisig-signer":"1913909","solana-worker-set-verifier":"1913909","solana-msg-verifier":"1913909"},"pub_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Ay37xIKJmkQLVPwgO6xzW8TcdtNXGSvxzaHcIjurb2Ci"}
# ```python3
# import base64
# # Extract the base64-encoded key
# key_base64 = "Ay37xIKJmkQLVPwgO6xzW8TcdtNXGSvxzaHcIjurb2Ci"
# # Decode the base64-encoded key to raw binary data
# key_bytes = base64.b64decode(key_base64)
# # Convert the raw binary data to a hexadecimal string
# key_hex = key_bytes.hex()
# print(key_hex)
# ```
address = "032dfbc482899a440b54fc203bac735bc4dc76d357192bf1cda1dc223bab6f60a2"
weight = 1
