[package]
name = "interchain-token-service"
version = "0.1.0"
description = "Port of the https://github.com/axelarnetwork/interchain-token-service/blob/c2ab974cc6e4ae719c744738023c89644ac2c8d4/contracts/InterchainTokenService.sol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program.workspace = true
thiserror.workspace = true
borsh.workspace = true
interchain-token-transfer-gmp.workspace = true
program-utils.workspace = true
num-derive.workspace = true
num-traits.workspace = true
gateway = { workspace = true, features = ["no-entrypoint"] }
token-manager = { workspace = true, features = ["no-entrypoint"] }
account-group = { workspace = true, features = ["no-entrypoint"] }
gas-service = { workspace = true, features = ["no-entrypoint"] }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-associated-token-account = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test.workspace = true
test-fixtures.workspace = true
solana-sdk.workspace = true
anyhow.workspace = true
