[package]
name = "axelar-solana-memo-program"
version = "0.1.0"
description = "Utility program to test Axelar Gateway and other integrations"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
axelar-executable = { workspace = true }
borsh.workspace = true
gateway = { workspace = true, features = ["no-entrypoint"] }
program-utils = { workspace = true }
solana-program.workspace = true

[dev-dependencies]
axelar-rkyv-encoding.workspace = true
ethers-core.workspace = true
evm-contracts-test-suite.workspace = true
itertools.workspace = true
rstest.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-fixtures.workspace = true
