[package]
name = "axelar-executable-old"
description = "Defines helpers for easily integrating with the Solana Axelar Gateway"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
axelar-message-primitives.workspace = true
axelar-rkyv-encoding.workspace = true
borsh.workspace = true
gateway.workspace = true
solana-program.workspace = true

[dev-dependencies]
