[package]
name = "amplifier-api-mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8" # fix for solana incompatibility
tonic = "0.10.2"
prost = "0.12.3"
tokio-stream = "0.1.14"
h2 = "0.4.0"
hex = "0.4.3"
cosmwasm-std = "1.5.0"
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread", "macros"] }
bcs = "0.1.6"
itertools = "0.12.0"
solana-program = "=1.18.0"
tiny-keccak = { version = "2.0.0", features = ["sha3"] }
cosmos-sdk-proto = "0.20.0"
cosmrs = { version = "0.15.0", features = ["cosmwasm"] }
serde_json.workspace = true
serde.workspace = true
tendermint = "0.34.0"
tendermint-rpc = { version = "0.34.0", features = [
    "websocket-client",
    "http-client",
] }
lazy_static = "1.4.0"
amplifier-api = { path = "../amplifier-api" }

[dependencies.uuid]
version = "1.6.1"
features = ["v4", "fast-rng", "macro-diagnostics"]

[dependencies.axelar-wasm-std]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.gateway]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.voting-verifier]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.connection-router]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.multisig]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.multisig-prover]
git = "https://github.com/axelarnetwork/axelar-amplifier"
rev = "c0904e1c72c99a174a93b5f6c18b30f52d20b71f"
features = ["library"]

[dependencies.gmp-gateway]
path = "../../../solana/programs/gateway"
features = ["no-entrypoint"]

[build-dependencies]
tonic-build = "0.10.2"
