[package]
name = "interchain-token-transfer-gmp"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers-core.workspace = true
token-manager.workspace = true

[dev-dependencies]
hex.workspace = true
