name: evm-contracts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "evm-contracts/**"

env:
  FOUNDRY_PROFILE: ci

defaults:
  run:
    working-directory: "evm-contracts"

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # foundry uses submodules for dependencies
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
