name: Continuous Integration for Solana Programs

on:
  push:
    branches: [main, poc]
    paths:
      - solana/**
      - .github/workflows/solana-programs.yml
  pull_request:
    branches: [main, poc]
    paths:
      - solana/**
      - .github/workflows/solana-programs.yml

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  RUSTFLAGS: "-D warnings"
  SCCACHE_GHA_ENABLED: "true"
  SOLANA_VERSION: "v1.17.7"

defaults:
  run:
    working-directory: solana
    shell: bash

jobs:
  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt"

      - name: Run rustfmt
        run: cargo fmt --check --all

  clippy:
    name: Clippy linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy"

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache compilation artifacts
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run clippy
        run: cargo clippy --all-targets

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache compilation artifacts
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run unit tests
        run: cargo test --workspace

  gateway-integration-tests:
    name: Gateway Program - Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Solana
        uses: actions/cache@v3
        with:
          path: ~/.cache/solana
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/${{ env.SOLANA_VERSION}}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache compilation artifacts
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run integration tests
        run: cargo-test-sbf --features test-sbf --package gateway
