on:
  push:
    branches: [main]
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: solana
    shell: bash    


name: test
jobs:
  test:
    runs-on: large-runner
    name: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo xtask test
        run: cargo xtask test
